{
 "title": "GRPC load balancing",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "grpc server (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_server_msg_received_total{container=~\"grpc-server\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grpc xds client total (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(grpc_xds_client_request_total{container=\"grpc-xds-client\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "grpc client total (rps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(grpc_client_request_total{container=\"grpc-client\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}