apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-client
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: bigphuc/grpc-example
          imagePullPolicy: Always
          args: [ "client", "-t", "dns:///grpc-server-grpc:50051", "-c", "100", "-d", "10m" ]
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-client
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: grpc-client
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpc-client
  namespace: example
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-client
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - example