apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: localhost:5001/grpc-example
          imagePullPolicy: Always
          args: [ "server", "-a", ":50051" ]
          env:
            - name: GRPC_GO_LOG_VERBOSITY_LEVEL
              value: "99"
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: info
          ports:
            - name: grpc
              containerPort: 50051
              protocol: TCP
            - name: metric
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: metric
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: metric
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-grpc
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-server
spec:
#  clusterIP: None
  type: ClusterIP
  ports:
    - port: 50051
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: grpc-server
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-server
spec:
  type: ClusterIP
  ports:
    - name: metric
      port: 8000
      targetPort: metric
      protocol: TCP
  selector:
    app.kubernetes.io/name: grpc-server
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grpc-server
  namespace: example
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-server
  endpoints:
    - port: metric
  namespaceSelector:
    matchNames:
      - example