apiVersion: v1
kind: ServiceAccount
metadata:
  name: xds-server-user
  namespace: example
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: example
  name: xds-server-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xds-server-rbac
subjects:
  - kind: ServiceAccount
    name: xds-server-user
    namespace: example
roleRef:
  kind: ClusterRole
  name: xds-server-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-xds
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-xds
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-xds
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpc-xds
    spec:
      serviceAccountName: xds-server-user
      containers:
        - name: grpc-xds
          image: bigphuc/grpc-example
          imagePullPolicy: Always
          args: [ "xds", "-i", "b7f9c818-fb46-43ca-8662-d3bdbcf7ec18",
                  "-d", "true", "-n", "example", "-s", "grpc-server-grpc" ]
          ports:
            - name: grpc
              containerPort: 18000
              protocol: TCP
            - name: metric
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: metric
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: metric
            initialDelaySeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-xds-grpc
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-xds
spec:
  type: ClusterIP
  ports:
    - port: 18000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: grpc-xds
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-xds
  namespace: example
  labels:
    app.kubernetes.io/name: grpc-xds
spec:
  type: ClusterIP
  ports:
    - name: metric
      port: 8000
      targetPort: metric
      protocol: TCP
  selector:
    app.kubernetes.io/name: grpc-xds
